[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oak"
version = "1.0.2"
description = "Oak Python package"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "numpy>=2.3.0,<3.0",
    "torch>=2.8.0,<3.0"
]

[project.scripts]
tutorial = "pyoak.tutorial:main"
battle   = "pyoak.battle:main"
rl       = "pyoak.rl:main"
build    = "pyoak.build:main"
elo      = "pyoak.elo:main"
