[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyoak"
version = "1.0.2"
description = "Oak Python package"
readme = "README.md"
requires-python = ">=3.11"